/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type WorkspaceRole = "member" | "owner" | "viewer";

export interface Workspace {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
}

export interface WorkspaceMember {
  created_at: Generated<Timestamp>;
  role: WorkspaceRole;
  user_id: string;
  workspace_id: string;
}

export interface DB {
  workspace: Workspace;
  workspace_member: WorkspaceMember;
}
